"""update columns of user table

Revision ID: ad7171ff0548
Revises: aa03f1a6fbdc
Create Date: 2026-01-05 10:32:55.601641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad7171ff0548'
down_revision: Union[str, Sequence[str], None] = 'aa03f1a6fbdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('userId', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('uniqueId', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False))
    op.add_column('users', sa.Column('isActive', sa.Boolean(), nullable=False))
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.create_index(op.f('ix_users_uniqueId'), 'users', ['uniqueId'], unique=True)
    op.create_index(op.f('ix_users_userId'), 'users', ['userId'], unique=True)
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_userId'), table_name='users')
    op.drop_index(op.f('ix_users_uniqueId'), table_name='users')
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.drop_column('users', 'isActive')
    op.drop_column('users', 'updatedAt')
    op.drop_column('users', 'createdAt')
    op.drop_column('users', 'uniqueId')
    op.drop_column('users', 'userId')
    # ### end Alembic commands ###
